baseURL = 'https://hunterwittenborn.com/'
languageCode = 'en-us'
title = 'Hunter Wittenborn'
theme = "PaperMod"
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[params]
ShowCodeCopyButtons = true
ShowReadingTime = true
ShowToc = true
TocOpen = true

[params.profileMode]
enabled = true
imageUrl = "/profile.jpg"

[[params.profileMode.buttons]]
name = "Blog"
url = "/blog"

[[params.socialIcons]]
name = "email"
url = "mailto:hunter@hunterwittenborn.com"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/hwittenborn/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/hwittenborn"

[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/hwittenborn"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/FtNhPepvj7"

[[params.socialIcons]]
name = "matrix"
url = "https://matrix.to/#/@hunter-wittenborn:matrix.org"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"
